version: '2'
services:

  database:
    image: flowgate/database:FLOWGATE_VERSION
    container_name: flowgate-database-container
    networks:
      - db-network
    volumes:
      - /opt/vmware/flowgate/data/database/data:/opt/couchbase/var
      - /opt/vmware/flowgate/conf/database/init.sh:/init.sh
      - /opt/vmware/flowgate/conf/database/initData.sh:/home/couchbase/initData.sh
    expose:
      - 8091
      - 8092
      - 8093
      - 8094
      - 8095
      - 8096
      - 11207
      - 11210
      - 11211
      - 18091
      - 18092
      - 18093
      - 18094
      - 18095
      - 18096
          
  redis:
    image: flowgate/redis:FLOWGATE_VERSION
    container_name: flowgate-redis-container
    expose:
      - 6379
    networks:
      - services-network
    volumes:
      - /opt/vmware/flowgate/data/redis:/var/lib/redis
      - /opt/vmware/flowgate/log/redis:/var/log/redis
      - /opt/vmware/flowgate/conf/redis/redis.conf:/etc/redis.conf
      
  flowgate-api:
    image: flowgate/api:FLOWGATE_VERSION
    volumes:
      - /opt/vmware/flowgate/log/flowgate-api:/log
      - /opt/vmware/flowgate/conf/flowgate-api:/conf
    container_name: flowgate-api-container
    networks:
      - db-network
      - services-network
    depends_on:
      - database
      - redis
    links:
      - database:database
      - redis:redis
    expose:
      - 49610
    environment:
      FLOWGATESERVICEKEY: serviceKey

  management:
    image: flowgate/management:FLOWGATE_VERSION
    volumes:
      - /opt/vmware/flowgate/log/management:/log
      - /opt/vmware/flowgate/conf/management:/conf
    container_name: flowgate-management-container
    ports:
      - 443:49611
    expose:
      - 443
      - 80
    networks:
      - services-network
      - db-network
    links:
      - database:database
      - redis:redis
      - flowgate-api:flowgate-api
    environment:
      FLOWGATESERVICEKEY: serviceKey

  aggregator:
    image: flowgate/aggregator:FLOWGATE_VERSION
    volumes:
      - /opt/vmware/flowgate/log/aggregator:/log
      - /opt/vmware/flowgate/conf/aggregator:/conf
    container_name: flowgate-aggregator-container
    networks:
      - services-network
    depends_on:
      - redis
      - flowgate-api
    links:
      - redis:redis
      - flowgate-api:flowgate-api
    environment:
      FLOWGATESERVICEKEY: serviceKey

  infoblox-worker:
    image: flowgate/infoblox-worker:FLOWGATE_VERSION
    volumes:
      - /opt/vmware/flowgate/log/infoblox-worker:/log
      - /opt/vmware/flowgate/conf/infoblox-worker:/conf
    container_name: flowgate-infoblox-worker-container
    networks:
      - services-network
    depends_on:
      - redis
      - flowgate-api
    links:
      - redis:redis
      - flowgate-api:flowgate-api
    environment:
      FLOWGATESERVICEKEY: serviceKey

  nlyte-worker:
    image: flowgate/nlyte-worker:FLOWGATE_VERSION
    volumes:
      - /opt/vmware/flowgate/log/nlyte-worker:/log
      - /opt/vmware/flowgate/conf/nlyte-worker:/conf
    container_name: flowgate-nlyte-worker-container
    networks:
      - services-network
    depends_on:
      - redis
      - flowgate-api
    links:
      - redis:redis
      - flowgate-api:flowgate-api
    environment:
      FLOWGATESERVICEKEY: serviceKey

  poweriq-worker:
    image: flowgate/poweriq-worker:FLOWGATE_VERSION
    volumes:
      - /opt/vmware/flowgate/log/poweriq-worker:/log
      - /opt/vmware/flowgate/conf/poweriq-worker:/conf
    container_name: flowgate-poweriq-worker-container
    networks:
      - services-network
    depends_on:
      - redis
      - flowgate-api
    links:
      - redis:redis
      - flowgate-api:flowgate-api
    environment:
      FLOWGATESERVICEKEY: serviceKey
      
  labsdb-worker:
    image: flowgate/labsdb-worker:FLOWGATE_VERSION
    volumes:
      - /opt/vmware/flowgate/log/labsdb-worker:/log
      - /opt/vmware/flowgate/conf/labsdb-worker:/conf
    container_name: flowgate-labsdb-worker-container
    networks:
      - services-network
    depends_on:
      - redis
      - flowgate-api
    links:
      - redis:redis
      - flowgate-api:flowgate-api
    environment:
      FLOWGATESERVICEKEY: serviceKey

  vc-worker:
    image: flowgate/vc-worker:FLOWGATE_VERSION
    volumes:
      - /opt/vmware/flowgate/log/vc-worker:/log
      - /opt/vmware/flowgate/conf/vc-worker:/conf
    container_name: flowgate-vc-worker-container
    networks:
      - services-network
    depends_on:
      - redis
      - flowgate-api
    links:
      - redis:redis
      - flowgate-api:flowgate-api
    environment:
      FLOWGATESERVICEKEY: serviceKey

  vro-worker:
    image: flowgate/vro-worker:FLOWGATE_VERSION
    volumes:
      - /opt/vmware/flowgate/log/vro-worker:/log
      - /opt/vmware/flowgate/conf/vro-worker:/conf
    container_name: flowgate-vro-worker-container
    networks:
      - services-network
    depends_on:
      - redis
      - flowgate-api
    links:
      - redis:redis
      - flowgate-api:flowgate-api
    environment:
      FLOWGATESERVICEKEY: serviceKey
      
  openmanage:
    image: flowgate/openmanage:FLOWGATE_VERSION
    volumes:
      - /opt/vmware/flowgate/log/openmanage:/log
      - /opt/vmware/flowgate/conf/openmanage:/conf
    container_name: flowgate-openmanage-container
    networks:
      - services-network
    depends_on:
      - redis
      - flowgate-api
    links:
      - redis:redis
      - flowgate-api:flowgate-api
    environment:
      FLOWGATESERVICEKEY: serviceKey

networks:
  db-network:
  services-network:
