name: test management

on:
  pull_request:
    paths:
      - 'management/**'

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: test management
      run: |
        export FLOWGATEPWD=$PWD
        cd $FLOWGATEPWD/flowgate-common
        sudo mvn clean install
        cd $FLOWGATEPWD/common-restclient
        sudo mvn clean install
        cd $FLOWGATEPWD/worker-jobs
        sudo mvn clean install
        cd $FLOWGATEPWD/management
        sudo mvn clean test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1